language: objective-c

branches:
 only:
 - master

xcode_project: "Smart_Alarm/Smart Alarm.xcodeproj"
xcode_scheme: "UI_Tests"
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project "Smart_Alarm/Smart Alarm.xcodeproj" -scheme "UI_Tests"